spin_version = "1"
authors = ["Radu Matei <radu.matei@fermyon.com>"]
name = "spin-llama2-chat"
trigger = { type = "http", base = "/" }
version = "0.1.0"

# Chat UI
[[component]]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.2/spin_static_fs.wasm", digest = "sha256:65456bf4e84cf81b62075e761b2b0afaffaef2d0aeda521b245150f76b96421b" }
id = "web"
files = [{ source = "web", destination = "/" }]
[component.trigger]
route = "/..."
watch = ["index.html", "main.js", "styles.css"]

# API
[[component]]
id = "api"
source = "api/target/spin-http-js.wasm"
key_value_stores = ["default"]
[component.trigger]
route = "/api/..."
[component.build]
command = "npm run build"
workdir = "api"
watch = ["src/index.ts", "package.json"]

